name: CD

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  auto-tag:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'releases/')
    runs-on: macos-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Get tag from branch
        id: get_tag
        run: |
          branch="${{ github.head_ref }}"
          version="${branch#releases/}"
          tag="$version"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.get_tag.outputs.tag }}
          git push origin ${{ steps.get_tag.outputs.tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: Release ${{ steps.get_tag.outputs.tag }}
          body: "Auto-generated release for ${{ steps.get_tag.outputs.tag }}."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
