name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
            persist-credentials: true
            token: ${{ secrets.GITHUB_TOKEN }}
            fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Verify tag source branch is dev
        run: |
          git fetch origin dev
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
          DEV_COMMIT=$(git rev-parse origin/dev)
          if [ "$TAG_COMMIT" != "$DEV_COMMIT" ]; then
            echo "❌ Tag must be created from the tip of dev branch."
            exit 1
          fi

      - name: Fetch dev and main branches
        run: |
            git fetch origin dev
            git fetch origin main

      - name: Merge dev into main
        run: |
          git checkout main
          git merge origin/dev --no-ff -m "Auto-merge dev into main on tag ${{ github.ref_name }}"
          git push origin main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Auto-generated release from tag ${{ github.ref_name }}."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
